### ISSUE TITLE
Brilliant!

### ISSUE THREAD

**Issue by Tormentor667** [xavieran/BaKGL#202]
I wonder, is this already fully playable?

**Comment by fredrik-hjarner** [comment]
Just chiming in because I just tried running BaKGL.

@Tormentor667 You can try to follow the installation instructions and see for yourself. I ran into problems when building/running on Ubuntu Desktop 24.04. GetFullMapIcon got an index that was too high for some reason causing a crash,  but I can now see cutscenes, move around, click on stuff. I haven't tried too much.

**Comment by xavieran** [comment]
Hi, no it's not fully playable yet - the main thing missing is combat, as well as a number of other small details. The issues list here gives some idea of what remains to be implemented.

@fredrik-hjarner if possible would you be able to share the save and log that the crash occurred at? It would help me to fix the issue.

**Comment by fredrik-hjarner** [comment]
> @fredrik-hjarner if possible would you be able to share the save and log that the crash occurred at? It would help me to fix the issue.

I found the issue. It was uninitialized integers.

In ui/fullMap.hpp

here:
```
    unsigned mPlayerPositionBaseIcon;
    unsigned mPlayerPositionIconOffset;
```

I tried this and then the crash went away:
```
    unsigned mPlayerPositionBaseIcon{0};
    unsigned mPlayerPositionIconOffset{0};
```

**Comment by xavieran** [comment]
Thanks for letting me know, I should probably start using clang-tidy for this stuff. Will fix this up.

**Comment by fredrik-hjarner** [comment]
> Thanks for letting me know, I should probably start using clang-tidy for this stuff. Will fix this up.

np. I tried running bakgl now after your improvements and now I experienced no crash.

**Comment by Tormentor667** [comment]
> Hi, no it's not fully playable yet - the main thing missing is combat, as well as a number of other small details. The issues list here gives some idea of what remains to be implemented.

This project is brilliant. I really can't wait to relive BaK with this port :) I wonder: Is it also compatible with foreign language versions?

**Comment by xavieran** [comment]
It can be run with a foreign language version but I don't have any foreign language copies so have never tested it out.. I suspect there may be some bugs. I also have a few hardcoded english words in my code. If you could email me a foreign language version I can give it a go.

**Comment by xavieran** [comment]
Thanks, I will try that out. It should be fairly easy to add new translations, you would just need to update the text in all the dialogs. I can provide the option to read the text as JSON files or something rather than from the original DDX files which should make it very easy. The only semi-difficult thing would be making new fonts for non latin languages.

**Comment by Tormentor667** [comment]
> It can be run with a foreign language version but I don't have any foreign language copies so have never tested it out.. I suspect there may be some bugs. I also have a few hardcoded english words in my code. If you could email me a foreign language version I can give it a go.

Sure thing, send me an email to info@realm667.com and I can share you the german version. This includes also the glyphs for example for ß, ü, ö, ä.
